import { z } from "zod";

const shortText = (max: number) => z.string().trim().min(1).max(max);
const longText = (max: number) => z.string().trim().min(1).max(max);
const publicUrl = z.string().trim().max(2048).refine(
  (value) => value.startsWith("/") || /^https?:\/\//.test(value),
  "Enter a full http(s) URL or a site-relative path beginning with /.",
);

const pillarSchema = z.object({
  index: shortText(4),
  label: shortText(70),
  title: shortText(100),
  text: longText(260),
  imageUrl: z.string().trim().max(2048),
});

const practiceSlideSchema = z.object({
  eyebrow: shortText(90),
  title: shortText(160),
  description: longText(330),
  note: shortText(150),
});

const futureResourceSchema = z.object({
  status: shortText(40),
  title: shortText(120),
  summary: longText(220),
  downloadUrl: z.string().trim().max(2048).refine(
    (value) => value === "" || value.startsWith("/") || /^https?:\/\//.test(value),
    "Enter a full http(s) URL, a site-relative path, or leave blank while the guide is in development.",
  ),
});

export const siteContentSchema = z.object({
  identity: z.object({
    brandName: shortText(60),
    endorsement: shortText(80),
    managementLine: longText(180),
    footerTagline: longText(180),
    footerMeta: shortText(100),
    copyrightLabel: shortText(80),
    contactEmail: z.string().trim().email().max(320),
    logoUrl: publicUrl,
  }),
  hero: z.object({
    eyebrow: shortText(90),
    headline: shortText(140),
    emphasis: shortText(80),
    intro: longText(360),
    issueNumber: shortText(30),
    issueReadTime: shortText(30),
    issueKicker: shortText(70),
    issueTitle: shortText(190),
    issueOpenLabel: shortText(80),
    leadTitle: shortText(140),
    leadButtonLabel: shortText(80),
    leadAriaLabel: shortText(180),
    leadUrl: publicUrl,
    imageUrl: publicUrl,
    imageAlt: shortText(220),
    formNote: longText(360),
    formPrivacyLinkLabel: shortText(80),
    frequency: shortText(80),
    audience: shortText(120),
  }),
  quiet: z.object({
    prefix: shortText(120),
    emphasis: shortText(180),
  }),
  navigation: z.object({
    insideLabel: shortText(80),
    sampleLabel: shortText(80),
    resourcesLabel: shortText(80),
    subscribeLabel: shortText(80),
    browseArchiveLabel: shortText(100),
    valueCtaLabel: shortText(100),
    fallbackSubscribeLabel: shortText(120),
  }),
  inside: z.object({
    eyebrow: shortText(90),
    heading: shortText(150),
    emphasis: shortText(120),
    intro: longText(300),
  }),
  pillars: z.array(pillarSchema).length(3),
  archive: z.object({
    eyebrow: shortText(90),
    heading: shortText(150),
    emphasis: shortText(100),
    leadNumber: shortText(30),
    readingTime: shortText(40),
    leadLabel: shortText(80),
    leadTitle: shortText(190),
    leadDescription: longText(360),
    annotationLabel: shortText(90),
    sideBriefs: z.array(z.object({ label: shortText(80), title: shortText(150) })).length(2),
  }),
  practice: z.object({
    eyebrow: shortText(90),
    intro: longText(220),
    slides: z.array(practiceSlideSchema).length(3),
  }),
  closing: z.object({
    eyebrow: shortText(90),
    heading: shortText(130),
    emphasis: shortText(90),
    description: longText(260),
    ctaLabel: shortText(80),
    artifactName: shortText(60),
    artifactSchedule: shortText(60),
    artifactTitle: shortText(100),
    artifactAudience: shortText(80),
    metaItems: z.array(shortText(60)).length(3),
  }),
  resources: z.object({
    eyebrow: shortText(90),
    title: shortText(150),
    emphasis: shortText(120),
    intro: longText(360),
    featured: z.object({
      number: shortText(30),
      status: shortText(50),
      category: shortText(90),
      title: shortText(150),
      description: longText(400),
      reviewTime: shortText(60),
      format: shortText(60),
      proofPoint: shortText(100),
      bullets: z.array(shortText(220)).length(3),
      downloadLabel: shortText(100),
      downloadUrl: publicUrl,
      note: longText(260),
    }),
    upcoming: z.array(futureResourceSchema).length(2),
  }),
  links: z.object({
    atsUrl: publicUrl,
    liveTrainingUrl: z.string().trim().max(2048).refine(
      (value) => value === "" || value.startsWith("/") || /^https?:\/\//.test(value),
      "Enter a full http(s) URL, a site-relative path, or leave blank until a training session exists.",
    ),
    linkedinUrl: publicUrl,
  }),
  footer: z.object({
    exploreLabel: shortText(60),
    elsewhereLabel: shortText(60),
    legalLabel: shortText(60),
    sampleLinkLabel: shortText(80),
    insideLinkLabel: shortText(100),
    atsLinkLabel: shortText(80),
    liveTrainingLabel: shortText(80),
    contactLinkLabel: shortText(80),
    linkedinLinkLabel: shortText(80),
    privacyLinkLabel: shortText(80),
    backToTopLabel: shortText(80),
  }),
});

export type SiteContent = z.infer<typeof siteContentSchema>;

export const SITE_CONTENT_KEY = "signal-weekly-site";

export const defaultSiteContent: SiteContent = {
  identity: {
    brandName: "Signal Weekly",
    endorsement: "A Signrl publication",
    managementLine: "Signal Weekly is a Signrl publication, managed by Signrl.",
    footerTagline: "Useful intelligence for your next consequential career decision.",
    footerMeta: "Made for career momentum",
    copyrightLabel: "© 2026 SIGNAL WEEKLY",
    contactEmail: "signalweeklyhq@gmail.com",
    logoUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663899346819/SqONCjkhpoZAPMjE.png",
  },
  hero: {
    eyebrow: "WEEKLY CAREER INTELLIGENCE",
    headline: "A sharper search starts with a better",
    emphasis: "signal.",
    intro: "One concise weekly briefing for mid-career and executive professionals navigating their next consequential move.",
    issueNumber: "ISSUE 014",
    issueReadTime: "06 MIN READ",
    issueKicker: "THIS WEEK’S SIGNAL",
    issueTitle: "What an ATS actually sees before a human ever does.",
    issueOpenLabel: "Open the briefing",
    leadTitle: "The Executive ATS Résumé Audit",
    leadButtonLabel: "Free download",
    leadAriaLabel: "Download the Executive ATS Résumé Audit PDF",
    leadUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663899346819/RHWORFZPTcCpUqFY.pdf",
    imageUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663899346819/rMtHWNmluaMtQIPa.jpg",
    imageAlt: "Elegant executive desk with layered papers and cobalt pen",
    formNote: "Free, once a week. Confirm your email to start. Unsubscribe whenever you need. By subscribing, you agree to our",
    formPrivacyLinkLabel: "Privacy Policy.",
    frequency: "New issue every Friday",
    audience: "For professionals and leaders in motion",
  },
  quiet: {
    prefix: "Not another job board.",
    emphasis: "A point of view on the decisions that change your career.",
  },
  navigation: {
    insideLabel: "Inside the brief",
    sampleLabel: "Sample issue",
    resourcesLabel: "Resources",
    subscribeLabel: "Get the briefing",
    browseArchiveLabel: "Browse sample issues",
    valueCtaLabel: "Explore the signal",
    fallbackSubscribeLabel: "Subscribe to Signal Weekly on Beehiiv",
  },
  inside: {
    eyebrow: "INSIDE THE BRIEFING",
    heading: "The search is complex.",
    emphasis: "The guidance shouldn’t be.",
    intro: "Every issue turns a high-stakes career moment into a small set of clear, usable moves.",
  },
  pillars: [
    { index: "01", label: "RÉSUMÉ SIGNAL", title: "Make the first scan count.", text: "Build an ATS-ready résumé that tells a recruiter what changed because you were in the room.", imageUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663899346819/TgevWfEsgboMGMxi.jpg" },
    { index: "02", label: "INTERVIEW PRACTICE", title: "Answer like a leader.", text: "Translate your experience into decisive stories for questions that are built to test your judgment.", imageUrl: "" },
    { index: "03", label: "OFFER STRATEGY", title: "Negotiate the whole role.", text: "Frame a confident conversation about pay, benefits, scope, and the platform you need to do your best work.", imageUrl: "" },
  ],
  archive: {
    eyebrow: "FROM THE ARCHIVE",
    heading: "A six-minute briefing.",
    emphasis: "Built to stay with you.",
    leadNumber: "SIGNAL WEEKLY / 012",
    readingTime: "READING TIME 06:14",
    leadLabel: "THE INTERVIEW EDITION",
    leadTitle: "When “why now?” is really asking whether you can lead change.",
    leadDescription: "Three ways to make a career transition sound intentional, confident, and useful to the organisation across the table.",
    annotationLabel: "THE REFRAME",
    sideBriefs: [
      { label: "COMPENSATION NOTE", title: "The question to ask before you name a number." },
      { label: "RÉSUMÉ NOTE", title: "Where quantified outcomes actually earn their space." },
    ],
  },
  practice: {
    eyebrow: "THE BRIEFING, IN PRACTICE",
    intro: "Thoughtful prompts for the moments that deserve more than a template answer.",
    slides: [
      { eyebrow: "THE POSITIONING PROBLEM", title: "Your résumé is not a biography. It is a business case.", description: "Turn a nonlinear career into a clear executive narrative that a recruiter can understand in a first scan.", note: "The issue: translating scope into a signal." },
      { eyebrow: "THE CONVERSATION PROBLEM", title: "Difficult questions are often invitations to lead.", description: "Prepare the executive-level answers that communicate judgment, self-awareness, and operating range under pressure.", note: "The issue: making a credible pivot in the room." },
      { eyebrow: "THE DECISION PROBLEM", title: "Compensation is one part of a larger mandate.", description: "Negotiate salary, equity, scope, and the conditions that make the next role genuinely worth accepting.", note: "The issue: asking with precision, not apology." },
    ],
  },
  closing: {
    eyebrow: "YOUR FRIDAY DESK NOTE",
    heading: "Make your next move",
    emphasis: "with more signal.",
    description: "Short, useful intelligence for the career decision in front of you.",
    ctaLabel: "Get Signal Weekly",
    artifactName: "SIGNAL WEEKLY",
    artifactSchedule: "FRIDAY / 08:00",
    artifactTitle: "CAREER INTELLIGENCE BRIEFING.",
    artifactAudience: "EXECUTIVE EDITION",
    metaItems: ["NO COST", "ONE ISSUE / WEEK", "LEAVE ANYTIME"],
  },
  resources: {
    eyebrow: "THE SIGNAL WEEKLY LIBRARY",
    title: "Practical documents for a more deliberate",
    emphasis: "next move.",
    intro: "Short, useful guides for the career decisions that deserve more than generic advice. Start with the document in front of you, then build from there.",
    featured: {
      number: "RESOURCE 001",
      status: "AVAILABLE NOW",
      category: "CAREER INTELLIGENCE",
      title: "The Executive ATS Résumé Audit",
      description: "A pre-submission checklist for making your real experience easier to read, search and verify—without turning your résumé into a keyword list.",
      reviewTime: "15-minute review",
      format: "6-page PDF",
      proofPoint: "Evidence-led guidance",
      bullets: ["Make a portal-ready version that preserves the important text.", "Map role language to experience you can credibly explain.", "Use a 30-second executive scan and reusable application log."],
      downloadLabel: "Download the free audit",
      downloadUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663899346819/RHWORFZPTcCpUqFY.pdf",
      note: "Educational guidance only. It cannot guarantee an interview or outcome.",
    },
    upcoming: [
      { status: "AVAILABLE NOW", title: "The Executive Interview Preparation Brief", summary: "A practical guide to preparing clear, credible answers for consequential conversations.", downloadUrl: "/manus-storage/main_49368bcd.pdf" },
      { status: "IN DEVELOPMENT", title: "The Whole-Role Negotiation Map", summary: "A framework for thinking beyond the headline number.", downloadUrl: "" },
    ],
  },
  links: {
    atsUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663899346819/RHWORFZPTcCpUqFY.pdf",
    liveTrainingUrl: "",
    linkedinUrl: "https://www.linkedin.com",
  },
  footer: {
    exploreLabel: "EXPLORE",
    elsewhereLabel: "ELSEWHERE",
    legalLabel: "LEGAL",
    sampleLinkLabel: "Sample issues",
    insideLinkLabel: "What you’ll get",
    atsLinkLabel: "ATS résumé audit",
    liveTrainingLabel: "Live training",
    contactLinkLabel: "Contact",
    linkedinLinkLabel: "LinkedIn",
    privacyLinkLabel: "Privacy Policy",
    backToTopLabel: "Back to top",
  },
};
